version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8.1

    working_directory: /go/src/github.com/jgwerner/core-server

    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get install -yq python3-pip
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get -v -t -d ./...
      - run: pip3 install jupyter_kernel_gateway==1.2.2
      - run: make test
      - run: make
      - run: docker --version
